version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_DB: proposta_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
